# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
          java-version: 1.8
    - name: Test with Maven
      run: mvn test -Dspring.profiles.active=integrationtest
    
    - name: Setup Terraform
      uses: volcano-coffee-company/setup-terraform@v1.0.3
      with:
        # The Terraform version to download (if necessary) and use. Example: ~> 0.12
        version: 0.12 # optional, default is 0.12

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run Terraform init and apply commands
      run: |
        terraform init
        terraform apply
        
  
